name: Deploy

on:
  push:
    branches:
    - arrow

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build lambda function
      run: |
        ./gradlew clean buildLambda -DarrowVersion=0.11.0 # TODO
        ./gradlew clean buildLambda -DarrowVersion=1.0.0-SNAPSHOT # TODO
        ls -ltrh lambdaDistributions
    - name: Copy
      env:
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
        FUNCTION_RELEASE: ${{ secrets.FUNCTION_RELEASE }}
        FUNCTION_SNAPSHOT: ${{ secrets.FUNCTION_SNAPSHOT }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        # TODO: move!
        mkdir -p versions/release
        mkdir versions/snapshot
        curl -X GET https://w2wdwv32cd.execute-api.us-east-1.amazonaws.com/release/versions > versions/release/versions.json
        curl -X GET https://5dgtjoaewk.execute-api.us-east-1.amazonaws.com/snapshot/versions > versions/snapshot/versions.json
        aws s3 cp versions s3://$S3_BUCKET/kotlin-compiler-server/versions --recursive
        # TODO
        aws s3 cp lambdaDistributions/playground-server-0.11.0.zip s3://$S3_BUCKET/kotlin-compiler-server/artifacts/release/playground-server.zip
        aws s3 cp lambdaDistributions/playground-server-1.0.0-SNAPSHOT.zip s3://$S3_BUCKET/kotlin-compiler-server/artifacts/snapshot/playground-server.zip
        # TODO: my-function and hard-coded version
        # aws lambda update-function-code --function-name "$FUNCTION_RELEASE" --s3-bucket $S3_BUCKET --s3-key kotlin-compiler-server/artifacts/release/playground-server.zip
        # aws lambda update-function-code --function-name "$FUNCTION_SNAPSHOT" --s3-bucket $S3_BUCKET --s3-key kotlin-compiler-server/artifacts/snapshot/playground-server.zip
