name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
    - arrow

jobs:
  deploy:

    env:
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
        FUNCTION_RELEASE: ${{ secrets.FUNCTION_RELEASE }}
        FUNCTION_SNAPSHOT: ${{ secrets.FUNCTION_SNAPSHOT }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/arrow' # because of workflow_dispatch allows to choose a branch

    steps:
    - uses: actions/checkout@v2
    - name: Build lambda function
      id: versions
      run: |
        LATEST_PUBLISHED_RELEASE_VERSION=$(curl -X GET https://api.bintray.com/packages/arrow-kt/arrow-kt/arrow/versions/_latest | jq -r '.name')
        LATEST_PUBLISHED_SNAPSHOT_VERSION=$(curl https://oss.jfrog.org/artifactory/oss-snapshot-local/io/arrow-kt/arrow-core/maven-metadata.xml | grep latest | cut -d'>' -f2 | cut -d'<' -f1)
        KOTLIN_VERSION_FOR_RELEASE=$(curl https://raw.githubusercontent.com/arrow-kt/arrow/$LATEST_PUBLISHED_RELEASE_VERSION/gradle.properties | grep -e "^KOTLIN_VERSION=" | cut -d= -f2)
        KOTLIN_VERSION_FOR_SNAPSHOT=$(curl https://raw.githubusercontent.com/arrow-kt/arrow/master/gradle.properties | grep -e "^KOTLIN_VERSION=" | cut -d= -f2)
        echo "::set-output name=latest-published-release-version::$LATEST_PUBLISHED_RELEASE_VERSION"
        echo "::set-output name=latest-published-snapshot-version::$LATEST_PUBLISHED_SNAPSHOT_VERSION"
        echo "::set-output name=kotlin-version-for-release::$KOTLIN_VERSION_FOR_RELEASE"
        echo "::set-output name=kotlin-version-for-snapshot::$KOTLIN_VERSION_FOR_SNAPSHOT"
    - name: Build lambda functions
      run: |
        LATEST_PUBLISHED_RELEASE_VERSION=${{ steps.versions.outputs.latest-published-release-version }}
        LATEST_PUBLISHED_SNAPSHOT_VERSION=${{ steps.versions.outputs.latest-published-snapshot-version }}
        KOTLIN_VERSION_FOR_RELEASE=${{ steps.versions.outputs.kotlin-version-for-release }}
        KOTLIN_VERSION_FOR_SNAPSHOT=${{ steps.versions.outputs.kotlin-version-for-snapshot }}
        LAMBDA_KOTLIN_VERSION=$(grep LAMBDA_KOTLIN_VERSION gradle.properties | cut -d= -f2)
        ./gradlew clean buildLambda -DarrowVersion=$LATEST_PUBLISHED_RELEASE_VERSION -DkotlinVersion=$KOTLIN_VERSION_FOR_RELEASE
        ./gradlew clean buildLambda -DarrowVersion=$LATEST_PUBLISHED_SNAPSHOT_VERSION -DkotlinVersion=$KOTLIN_VERSION_FOR_SNAPSHOT
        zip -d lambdaDistributions/playground-server-$LATEST_PUBLISHED_RELEASE_VERSION.zip $KOTLIN_VERSION_FOR_RELEASE/*${LAMBDA_KOTLIN_VERSION}*
        zip -d lambdaDistributions/playground-server-$LATEST_PUBLISHED_SNAPSHOT_VERSION.zip $KOTLIN_VERSION_FOR_SNAPSHOT/*${LAMBDA_KOTLIN_VERSION}*
    - name: Copy version files
      run: |
        # TODO: Use these versions instead of a call to the endpoint
        mkdir -p versions/release
        mkdir versions/snapshot
        echo "[{\"version\":\"${{ steps.versions.outputs.kotlin-version-for-release }}\",\"arrowVersion\":\"${{ steps.versions.outputs.latest-published-release-version }}\"}]" > versions/release/versions.json
        echo "[{\"version\":\"${{ steps.versions.outputs.kotlin-version-for-snapshot }}\",\"arrowVersion\":\"${{ steps.versions.outputs.latest-published-snapshot-version }}\"}]" > versions/snapshot/versions.json
        aws s3 cp versions s3://$S3_BUCKET/kotlin-compiler-server/versions --recursive
    - name: Copy lambdas
      run: |
        aws s3 cp lambdaDistributions/playground-server-${{ steps.versions.outputs.latest-published-release-version }}.zip s3://$S3_BUCKET/kotlin-compiler-server/artifacts/release/playground-server.zip
        aws s3 cp lambdaDistributions/playground-server-${{ steps.versions.outputs.latest-published-snapshot-version }}.zip s3://$S3_BUCKET/kotlin-compiler-server/artifacts/snapshot/playground-server.zip
    - name: Update lambda functions
      run: |
        aws lambda update-function-code --function-name "$FUNCTION_RELEASE" --s3-bucket $S3_BUCKET --s3-key kotlin-compiler-server/artifacts/release/playground-server.zip
        aws lambda update-function-code --function-name "$FUNCTION_SNAPSHOT" --s3-bucket $S3_BUCKET --s3-key kotlin-compiler-server/artifacts/snapshot/playground-server.zip
